# this file provides an example of how to use the colortable module

# import the module
import colortable as ct

# define the data
# for this example, the data are hard-coded, but for the actual project, they
# will be generated by the program
data = [['',  'A',  'a'],
        ['a', 'Aa', 'aa'],
        ['a', 'Aa', 'aa']]

# create a colortable out of the data
table = ct.colortbl(data)

# make a cell a single color
table.color(1, 2, c1='#fcaba4')
table.color(2, 2, c1='#fcaba4')

# make a cell split color
table.color(1, 1, c1='#fcaba4', c2='#a4c4fc')
table.color(2, 1, c1='#fcaba4', c2='#a4c4fc')

# display the table with matplotlib
table.show()
