#!/usr/bin/env python

# there is some hard link trickery going on here
# hopefully this is cross-system workable
import cgitb, allele

# these will be retrieved from HTTP POST once this is working okay
father = 'Aa'
mother = 'Aa'

# plot the punnett square
psquare = allele.plot(father, mother, title='example')
psquare.color(1, 1, c1='#a4c4fc')
psquare.color(2, 2, c1='#fcaba4')
psquare.color(1, 2, c1='#fcaba4', c2='#a4c4fc')
psquare.color(2, 1, c1='#fcaba4', c2='#a4c4fc')

# print the image to stdout
cgitb.enable()
print 'Content-Type: image/png'
print ''
print psquare.to_png()
