#!/usr/bin/env python

# these imports will not work until /setup.sh is run
# you can include cgitb for pretty errors, but that's not necessary
import os, urllib2, re, allele

# retrieve and parse HTTP GET request
os.environ['QUERY_STRING'] = 'father=Aa&mother=Aa'
query = [i.split('=')[1] for i in os.getenv('QUERY_STRING').split('&')]
father = query[0]
mother = query[1]
title = ''
if len(query) > 2:
    title = urllib2.unquote(query[2])

# validate data on server-side
test = re.compile('^[a-zA-Z]{2,8}$')
if (not bool(test.match(father)) or not bool(test.match(mother)) or
   len(father) != len(mother) or len(father) % 2 == 1):
    print 'Content-Type: text/html'
    print ''
    print 'Error: invalid query'
else:
    # solve the punnett square
    square = allele.solve(father, mother)
    colors = allele.colorize(square)

    # print the generated html table to stdout
    print 'Content-Type: text/html'
    print ''
    print allele.to_html(square, colors)
